# Generated by Django 4.1 on 2022-09-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_feature_event_category_alter_event_is_private_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
