# Generated by Django 4.1 on 2022-09-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_enroll_count',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Количество записей'),
        ),
    ]
