# Generated by Django 4.1 on 2022-09-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_show_enroll_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='show_enroll_count',
            new_name='filter_enroll_count',
        ),
    ]
