# Generated by Django 4.1 on 2022-09-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_filter_enroll_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enroll_count',
            field=models.CharField(default='', max_length=6, verbose_name='Количество записей'),
        ),
    ]
