# Generated by Django 4.1 on 2022-09-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_enroll_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='places_left_count',
            field=models.CharField(default='', max_length=10),
        ),
    ]
