# Generated by Django 4.1 on 2022-10-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_places_left_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='events/events'),
        ),
    ]
